export {
  USER_RECORDS_QUERY,
  DAILY_USER_RECORD_QUERY,
  APPOINTMENT_QUERY,
  OPENDAY_QUERY,
} from "./query";

export {
  LOGIN_MUTATION,
  CREATE_USER_MUTATION,
  DELETE_USER_MUTATION,
  CHANGE_USERNAME_MUTATION,
  CHANGE_PASSWORD_MUTATION,
  CREATE_APPOINTMENT_MUTATION,
  DELETE_APPOINTMENT_MUTATION,
  CREATE_RECORD_MUTATION,
  CREATE_OPENDAY_MUTATION,
  DELETE_OPENDAY_MUTATION,
} from "./mutation";

export {
  APPOINTMENT_SUBSCRIPTION,
  PATIENT_RECORD_SUBSCRIPTION,
  PATIENT_RECORD_DATE_SUBSCRIPTION,
} from "./subscription";
