export {
  USER_RECORDS_QUERY,
  DAILY_USER_RECORD_QUERY,
  APPOINTMENT_QUERY,
} from "./query";

export {
  LOGIN_MUTATION,
  CHANGE_PASSWORD_MUTATION,
  CREATE_APPOINTMENT_MUTATION,
  DELETE_APPOINTMENT_MUTATION,
  CREATE_RECORD_MUTATION,
} from "./mutation";
